name: workflow

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: start message
        run: echo "Starting data pipeline"
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.8'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directories
        run: |
          mkdir -p data/plots
          mkdir -p data/model

      - name: Run data pipeline
        run: |
          cd data
          python CNNCifar10Mock-1.py

      - name: Check for changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --staged --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Commit and push if changes
        if: env.changes == 'true'
        run: |
          git commit -m "update data hyperparameters"
          git push

      - name: Debug
        run: |
          echo "Checking contents of the directory"
          ls -R data/

      # Ensure that the plots are saved and available for download
      - name: Save generated plot
        uses: actions/upload-artifact@v3
        with:
          name: generated-plot
          path: data/plots/training_history.png  # Make sure this file is being generated and saved in the correct path

      # Ensure that the model is saved and available for download
      - name: Save model
        uses: actions/upload-artifact@v3
        with:
          name: cnn-model  # Name your model artifact for easy identification
          path: data/model/cnn_cifar10.h5  # Make sure this file is saved at this path by your training script
